### PR TITLE
Improvements to Sink Tool and general code

### PR DESCRIPTION
**Pull request by Hornbydd**
The following updates are to show how the the UI for a python toolbox tool can be improved, I have been in discussion with John about it. A test to see if I have understand how git hub functions I have improved only the Sink tool. The following edits were:

1] Make input parameter a raster layer so it can be accessed from the map.
2] Create a simple function to convert layer objects to full path which is required by WBT.
3] Amended the item description so parameters now provide useful information when you click on them.
4] Created a nice image that displays in tool.
5] Directly edited the WBT python module and put in a flag that hides the windows command line window that needlessly appears so tool behaves more like existing tools.

### CODE REVIEW

**Comment by giswqs** [comment]
@Hornbydd Hello Duncan, many thanks for the excellent suggestions! The only problem is that the ArcGIS front-end ([WhiteboxTools.pyt](https://github.com/giswqs/WhiteboxTools-ArcGIS/blob/master/WhiteboxTools.pyt)) is automatically generated using a Python script ([automation.py](https://github.com/giswqs/WhiteboxTools-ArcGIS/blob/master/WBT/PRE/automation.py)) whenever Dr. John Lindsay releases a new WBT version. Therefore, I try to avoid editing individual tools manually within the WhiteboxTools.pyt. Manual changes will be overwritten when [automation.py](https://github.com/giswqs/WhiteboxTools-ArcGIS/blob/master/WBT/PRE/automation.py) is executed to generate a new version. Nevertheless, I will improve the automation script and make systematic changes (instead of individual tool changes) based on your suggestions. Hope to work on this sometime next week. Thanks.

**Comment by Hornbydd** [comment]
OK I see the problem, particularly implementing the parameter information as that is essentially free text and one wants to guide the user, although it is a separate xml file would could be updated independently. It is WhiteboxTools.Sink.pyt.xml, so every other tool would have their own xml file.  

One could define the tool using your script and maintain a separate XML file which simply sits at the level of the pyt file. I think as long as the tool parameters are not changing with every version (would be a crazy tool by John!) then one only has to copy the xml created as your automation code is not creating the xml file.

I think all input rasters should be a raster layer so you can access them from within ArcMap and as you'll see in the code it is a simple function to return the  full path that WBT needs.

Note I have edited the WBT python module to hide the windows command line window.

**Comment by Hornbydd** [comment]
I had a feeling that I had come across this issue before on GIS SE. Someone wanted to document their python toolbox in an automated way. This[ Q&A ](https://gis.stackexchange.com/questions/317308/python-toolbox-documentation-from-within-pyt-file) thread would certainly support your approach in automating the generation of the tools. Well worth a look.

**Comment by giswqs** [comment]
@Hornbydd Thanks to your suggestions, I have resolved the following issues:

- hide the command line windows when a tool is executed
- input raster/vector layer can now be selected from the map (i.e., ArcGIS TOC)

Regarding the ~400 XML documentation files automatically generated by ArcGIS, I prefer not to have them under the root directory where the main Toolbox file (i.e., WhiteboxTools.pyt) is located. It is overwhelming. I intentionally ignored those XML files when pushing the repo to GitHub. When you click the "Show Help" button on each tool, you should be able to see the direct hyperlink to the [WhiteboxTools User Manua](https://jblindsay.github.io/wbt_book). Unless those XML files can be moved into a sub-folder and ArcGIS can still recognize them, I prefer not to include them.

**Pull request closed without merging**
